[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_voting = "2zDXpazUQnnm1R7FXkt61TSJ54nhAjTBDf5FxZvkJmYs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
